apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/YOUR_GITHUB_USERNAME/eks-argocd-demo.git
    targetRevision: main
    path: canary

  destination:
    server: https://kubernetes.default.svc
    namespace: stagens

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
