apiVersion: v1
kind: Namespace
metadata:
  name: devprojectns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: devprojectns
  labels:  # to map it with the service
    app: web
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
      env: dev
  template:
    metadata:
      name: webapp
      labels:
        app: web
        env: dev
    spec:
      containers:
        - name: webcon
          image: sudarshanlnx/farmfresh:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: apache
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
            limits:
              memory: "300Mi"
              cpu: "400m"
---
apiVersion: v1
kind: Service
metadata:
  name: websvc   # service name (it can be any name)
  namespace: devprojectns
spec:
  type: LoadBalancer
  ports:
    - name: apache
      port: 80          # service port
      targetPort: 80    # container port
      protocol: TCP
  selector:     # mapping to pod
    app: web
    env: dev
