apiVersion: v1
kind: Namespace
metadata:
  name: devprojectns
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: kuard
  namespace: devprojectns
  labels:
    app: kuard
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
        - name: kuard
          image: simplebyte/simplybyte-calculator:1.0  # change to :green to trigger blue-green rollout
          ports:
            - containerPort: 8080
  strategy:
    blueGreen:
      activeService: kuardsvc
      previewService: kuardsvc-preview
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 30
---
# ACTIVE
apiVersion: v1
kind: Service
metadata:
  name: kuardsvc
  namespace: devprojectns
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30090   # changed from 30080
  selector:
    app: kuard
---
# PREVIEW
apiVersion: v1
kind: Service
metadata:
  name: kuardsvc-preview
  namespace: devprojectns
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30091   # changed from 30081
  selector:
    app: kuard
